language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage sharedJVM/test sharedJS/test server/test coverageReport 'set scalaJSStage in Global := FullOptStage' &&
    sbt coverageAggregate
after_success:
  - sbt coveralls
scala:
   - 2.12.6
jdk:
  - openjdk8

